Add Quick Start

diff --git a/.github/workflows/management_resources.yml b/.github/workflows/management_resources.yml
--- a/.github/workflows/management_resources.yml
+++ b/.github/workflows/management_resources.yml
@@ -2,61 +2,76 @@ name: Management RG Deployment
 on:
   workflow_dispatch:
     inputs:
+      deployConnectivity:
+        description: 'Deploy Connectivity Resource Group'
+        type: boolean
+        required: false 
       location:
         description: 'Resource Group location'
         required: true
         default: 'westus2'
         type: string
-  
+
+permissions:
+  id-token: write # This is required for requesting the JWT
+  contents: read  # This is required for actions/checkout
+
 jobs:
 
   Connectivity_Resources:
     name: Create Connectivity Resources
     runs-on: ubuntu-latest
+    if: ${{ github.event.inputs.deployConnectivity == 'true' }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
-      - name: Login to Azure
+      - name: OIDC Login to Azure Public Cloud
         uses: azure/login@v1
         with:
-          creds: ${{secrets.AZURE_CREDENTIALS}}
-      - name: Create Resources
-        id: task-create-resources
-        uses: azure/CLI@v1
-        with:
-          azcliversion: 2.30.0
-          inlineScript: |
-            {
+          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
+      - name: 'Run az commands'
+        run: |
+          az account show
+          az group list
+      # - name: Create Resources
+      #   id: task-create-resources
+      #   uses: azure/CLI@v1
+      #   with:
+      #     azcliversion: 2.30.0
+      #     inlineScript: |
+      #       {
               
-              #######################################################
-              # Connectivity RG
-              #######################################################
-              # Resource Group
-              rg_region=westus2
-              rg_name=rg_connectivity_$rg_region
+      #         #######################################################
+      #         # Connectivity RG
+      #         #######################################################
+      #         # Resource Group
+      #         rg_region=westus2
+      #         rg_name=rg_connectivity_$rg_region
 
-              # Core VNet
-              vnet_core=vnet-core-$rg_region
-              vnet_core_prefix='10.0.0.0/16'
-              subnet_aad_ds=snet-add-ds # Core - Azure AD Domain Services subnet
-              subnet_aad_ds_prefix='10.0.255.0/27'
-              subnet_bastion=AzureBastionSubnet
-              subnet_bastion_prefix='10.0.255.64/27'
+      #         # Core VNet
+      #         vnet_core=vnet-core-$rg_region
+      #         vnet_core_prefix='10.0.0.0/16'
+      #         subnet_aad_ds=snet-add-ds # Core - Azure AD Domain Services subnet
+      #         subnet_aad_ds_prefix='10.0.255.0/27'
+      #         subnet_bastion=AzureBastionSubnet
+      #         subnet_bastion_prefix='10.0.255.64/27'
 
-              # Development VNet 
-              vnet_dev=vnet-dev-$rg_region
-              vnet_dev_prefix='10.1.0.0/16'
-              subnet_dev=snet-dev
-              subnet_dev_prefix='10.1.1.0/24'
+      #         # Development VNet 
+      #         vnet_dev=vnet-dev-$rg_region
+      #         vnet_dev_prefix='10.1.0.0/16'
+      #         subnet_dev=snet-dev
+      #         subnet_dev_prefix='10.1.1.0/24'
 
-              $deployment_script = "pipelines/management/connectivity.sh"
+      #         $deployment_script = "pipelines/management/connectivity.sh"
 
-              sh $deployment_script
+      #         sh $deployment_script
               
               
-            } || {
-              echo Failed creating connectivity resource group 
-            }
+      #       } || {
+      #         echo Failed creating connectivity resource group 
+      #       }
 
   Invoke_AutomationAccountPostDeployment:
     name: Invoke Automation Account Post Deployment
